export function createInitialState() {
  return {
    initialized: false,
    image: null,
    width: 0,
    height: 0,
    bands: 0,
    wavelengths: [],
    cie: null,
    stripScale: null,
    stripAxisBaseline: 12,
    bandCache: new Map(),
    spectrumCache: new Map(),
    fullRaster: null,
    pendingBandRequestId: 0,
    pendingSpectrumRequestId: 0,
    pendingSpectrumKey: null,
    currentSpectrum: [],
    currentSpectrumKey: null,
    activeBandIndex: 0,
    displayBandIndex: 0,
    hoverBandIndex: null,
    activePixel: null,
    displayPixel: null,
    hoverPixel: null,
    displayMin: 0,
    displayMax: 1,
    autoRange: true,
    selectedSpectrum: null,
    hoverSpectrum: null,
    globalMin: Infinity,
    globalMax: -Infinity,
    globalYAxisMax: 10,
    isStripPointerActive: false,
    isImagePointerActive: false,
  };
}
